name: Man10CheckerGradle
main: mabowdoufu.man10checkersgradle.Man10Checkers
version: 1.0.0
api-version: 1.21.8
author: mabowdoufu
description: Man10CheckerGradle plugin for Paper 1.21.8
commands:
  mcheckers:
    description: Man10Checkers
    usage: /mcheckers helpでコマンドを確認

permissions:
  mcheckers.op:
    default: op